image:
    file: .gitpod.Dockerfile

ports:
    - port: 9000
      onOpen: ignore

tasks:
    - init: composer install

vscode:
    extensions:
        - recca0120.vscode-phpunit@2.0.72:vLEnRmp0ao9i6Mig+25BuQ==
        - bmewburn.vscode-intelephense-client@1.3.11:w7xbYI5q5Cfv+1GBejftKg==
        - hbenl.vscode-test-explorer@2.18.0:vdCRJ/Ymtg3XxeNBz8PyMA==
        - felixfbecker.php-debug@1.13.0:WX8Y3EpQk3zgahy41yJtNQ==
